insta/urls.py
from django.contrib import admin
from django.urls import path,include
from insta import views
app_name='facebook'
urlpatterns = [
    path('home/', views.index,name='home'),
    path('home/<int:pk>/', views.profile_detail,name='profile_detail'),
    path('home/profile_detail_user/<str:user>/', views.profile_detail_user,name='profile_detail_user'),
    path('home/post_User_Post_commt/<int:pk>/', views.Post_commt.as_view(),name='post_User_Post_commt'),
    path('home/frnds_confirm/<str:user>/', views.frnds_confirm,name='frnds_confirm'),
    path('frnd_add/<int:pk>/', views.frnd_add,name='frnd_add'),
    path('frnds_unfrnds/<int:pk>/', views.frnds_unfrnds,name='frnds_unfrnds'),
    path('register_user/', views.register_user,name='register_user'),
    path('', views.user_login,name='user_login'),
]

soical/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('insta/', include('insta.urls',namespace='facebook')),
    path('', include('insta.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insta/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.shortcuts import reverse
# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver



class Profile(models.Model):
    profile_pic = models.ImageField(upload_to='media/profile_pic/',blank=True,null=True,default='nopic/slide3.jpg')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=200,blank=True,null=True)
    phone_no = models.CharField(validators=[RegexValidator("^0?[5-9]{1}\d{9}$")], max_length=15, null=True, blank=True)
    def __str__(self):
        return self.user.username

    def get_profle_url(self):
        return reverse('facebook:profile_detail',kwargs={'pk': self.id})

    def get_add_frind_url(self):
        return reverse('facebook:frnd_add', kwargs={'pk': self.id})

    def get_add_frind_confirm_url(self):
        return reverse('facebook:frnds_confirm',  kwargs={'user': self.user})

    def get_add_frind_unfrnds_url(self):
        return reverse('facebook:frnds_unfrnds',  kwargs={'pk': self.id})
    # def get_add_frind_del_url(self):
    #     return reverse('facebook:frnds_del',  kwargs={'pk': self.id})

    def get_request_Profile_url(self):
        return reverse('facebook:profile_detail_user', kwargs={'user': self.user})





class User_Post(models.Model):
    pic = models.ImageField(upload_to='post/')
    subject = models.CharField(max_length=200)
    msg = models.TextField(null=True, blank=True)
    cr_date = models.DateTimeField(auto_now_add=True)
    uploaded_by = models.ForeignKey(Profile,on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return "%s" % self.subject


class AddFriend(models.Model):
    add =models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='add')
    add_by =models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='add_by')
    send_rqst = models.BooleanField(default=False)
    confirmn= models.BooleanField(default=False)
    def __str__(self):
        return '%s (%s)'%(self.add ,self.add_by)

class User_Post_commt(models.Model):
    post =models.ForeignKey(User_Post,on_delete=models.CASCADE,related_name='post')
    commt =models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='commt')
    you_msg= models.CharField(null=True,blank=True,max_length=250)
    def __str__(self):
        return '%s (%s)'%(self.post ,self.commt)

   
    




@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

insta/forms.py
from django import forms
from django.forms import ModelForm, Textarea, TextInput,Select,FileInput,HiddenInput
from insta.models import Profile,User_Post,AddFriend,User_Post_commt

class User_Postform(forms.ModelForm):
    class Meta:
        model = User_Post
        # fields = '__all__'
        fields = ['subject','msg','pic']

class AddFriend_form(forms.ModelForm):
    class Meta:
        model =AddFriend
        fields= ['add_by','add','confirmn']
        # widgets = {
        #     'add': HiddenInput(attrs={
        #         'autocomplete': 'off'}),
        #     'add_by': HiddenInput(attrs={
        #         "class": "bg-white rounded border border-red-400 focus:outline-none focus:border-indigo-500 text-base px-4 py-2 mb-4 mt-0"}),
        #     'confirmn': HiddenInput(attrs={
        #         "class": "bg-white rounded border border-red-400 focus:outline-none focus:border-indigo-500 text-base px-4 py-2 mb-4 mt-0"}),
        # }

class User_Post_commtform(forms.ModelForm):
    class Meta:
        model =User_Post_commt
        fields= ['you_msg']

insta/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth import authenticate,login
from django.contrib.auth.forms import AuthenticationForm
from .models import Profile,User_Post,AddFriend,User_Post_commt
from .forms import User_Postform,AddFriend_form,User_Post_commtform
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
# Create your views here.
@login_required
def index(request):
    # profile_D = Profile.objects.all()
    k =request.user


    your_post = User_Post.objects.filter(uploaded_by__user=k)
  
    profile =None
    jquery = request.GET.get('jquery')
    if jquery:
        profile = Profile.objects.filter(user__username__icontains=jquery)
    else:
        profile = User_Post.objects.filter(uploaded_by__user=k).order_by('-id')
    username = request.user
    user_profile = Profile.objects.get(user=request.user)

    # print(user_profile)
    post = User_Postform()
    if request.method == 'POST':
        post = User_Postform(request.POST,request.FILES)
        if post.is_valid():
            form = post.save()
            form.uploaded_by = user_profile

            form.save()
            return redirect('facebook:home')
 

    parm={
        'profile':profile,
        'post':post
    }
    return render(request, 'insta/index.html',parm)


# class profile_detail(DetailView):
#     model = Profile
@login_required
def profile_detail(request,pk):
    profile_D = get_object_or_404(Profile,id=pk)
    userId = profile_D.user   
    user=request.user.username
    post_D = User_Post.objects.filter(uploaded_by__user=userId)
    add_frnds =AddFriend_form()
    check_frnds = AddFriend.objects.filter(add_by__user__username=userId,send_rqst=True,confirmn=False)
    
    if request.method == 'POST':
       post = request.POST.get('post')
       you_msg = request.POST.get('you_msg')
       user_profile = Profile.objects.get(user=request.user)
       commment_post = User_Post.objects.get(id=post)
       commment = User_Post_commt(commt=user_profile,post=commment_post,you_msg=you_msg)
       commment.save()
     
    parm= {
        'profile_D':profile_D,
        'post':post_D,
        'add_frnds':add_frnds,
        'check_frnds':check_frnds,
        # 'commment_count':commment_count,
        # 'commment':commment
           }
    return render(request,'insta/profile_detail.html',parm)

@login_required
def frnd_add(request,pk):
    k =  get_object_or_404(Profile,id=pk)
    p= k.user.username
 
    username = request.user
    profile = Profile.objects.get(user=username)
    profile_buy = Profile.objects.get(user__username=p)
    frnd_request,created = AddFriend.objects.get_or_create(add=profile,add_by=profile_buy,confirmn=False,send_rqst=True)
    frnd_request.save()
    return redirect('facebook:profile_detail',pk=pk)

@login_required
def profile_detail_user(request,user):
    user = request.user.username

    user_detail_id = get_object_or_404(Profile,user__username=user)
  
    profile_post = User_Post.objects.filter(uploaded_by=user_detail_id)
    frndRequest = AddFriend.objects.filter(add_by__user__username=user,confirmn=False)
    you_frnds = AddFriend.objects.filter(add_by__user__username=user,confirmn=True)
    
  

    parm ={
       'user_profile_detail':user_detail_id,
       'profile_post':profile_post,
       'frndRequest':frndRequest ,
       'you_frnds':you_frnds,
     
    }
    return render(request,'insta/profile_detail_user.html',parm)
@login_required
def frnds_confirm(request,user):
    user = request.user.username

    user_detail_id = get_object_or_404(Profile,user__username=user)
    conf = AddFriend.objects.filter(add_by__user__username=user).update(confirmn=True)
    return redirect('facebook:profile_detail_user',user=user)
@login_required
def frnds_unfrnds(request,pk):
    k =  get_object_or_404(Profile,id=pk)
    p= k.user.username
    username = request.user
    profile = Profile.objects.get(user=username)
    profile_buy = Profile.objects.get(user__username=p)
    frnd_request = AddFriend.objects.get(add=profile,add_by=profile_buy,confirmn=False,send_rqst=True).delete()
    return redirect('facebook:profile_detail',pk=pk)



class Post_commt(View):
    """docstring for ClassName"""
    def get(self, *args, **kwargs):
        
        # print(profile_D)
        profile_D=kwargs['pk']
        print('id',profile_D)
        a = User_Post.objects.get(id=profile_D)

        print(a)
        commt= User_Post_commt.objects.filter(post_id=profile_D)
        print('commt',commt)

       
   
        parm={
        'profile_D':a,
        'commt':commt,
        }
        
        return render(self.request, 'insta/post_User_Post_commt.html',parm)
    def post(self,request,*args, **kwargs):
        pk=kwargs['pk']
        if request.method == 'POST':
           post = request.POST.get('post')
           you_msg = request.POST.get('you_msg')
           user_profile = Profile.objects.get(user=request.user)
           commment_post = User_Post.objects.get(id=post)
           commment = User_Post_commt(commt=user_profile,post=commment_post,you_msg=you_msg)
           commment.save()
        return HttpResponseRedirect(request.path_info)







@login_required
def user_login(request):
    if request.user.is_authenticated:
        return redirect('facebook:home')
    else:
        form = AuthenticationForm()
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user =authenticate(username=username,password=password)
            if user is None:
               return redirect('facebook:user_login')
            else:
                login(request,user)
                return redirect('facebook:home')
        else:
            return render(request,'insta/user_login.html',{'form':form})

def register_user(request):
    if request.user.is_authenticated:
        return redirect('facebook:home')
    else:
        if request.method == 'POST':
            username = request.POST.get('Username')
            email = request.POST.get('email')
            password1 = request.POST.get('password1')
            user = User.objects.create_user(username=username,password=password1,email=email)
            user.save()
            return redirect('facebook:user_login')
        else:
            return render(request,'insta/register_user.html')

templates/insta/e-com.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>

</body>
</html>

templates/insta/index.html
 {% extends 'base.html'%}

  {% block contect %}
<section class="text-gray-700 body-font w-1/2 " style="background-color: gray; margin-left: 270px; ">
  <div class="container px-1 py-4 mx-auto flex flex-wrap flex-col">
    <div class="flex mx-auto flex-wrap mb-20" >
    <div class="flex flex-col text-center w-full mb-12" >
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Your Post</h1>
    
    </div>
    <div class="lg:w-full md:w-full mx-auto">
      <div class="flex flex-wrap ">
       <form method="POST" enctype="multipart/form-data" id="">
             {% csrf_token %}
          <div class="p-0 w-w-ful">
         <!--  <input class="w-full bg-gray-100 rounded border border-gray-400 focus:outline-none focus:border-indigo-500 text-base px-4 py-2" placeholder="Email" type="file"> -->
         {{post.pic}}
        </div>
        <div class="p-2 w-full">
<!--           <input class="w-full bg-gray-100 rounded border border-gray-400 focus:outline-none focus:border-indigo-500 text-base px-4 py-2" placeholder="subject" type="text"> -->
{{post.subject}}
        </div>
      
        <div class="p-2 w-full">
         <!--  <textarea class="w-full bg-gray-100 rounded border border-gray-400 focus:outline-none h-48 focus:border-indigo-500 text-base px-4 py-2 resize-none block" placeholder="what's on your mind?"></textarea> -->
         {{post.msg}}
        </div>
        <div class="p-2 w-full">
          <button class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg" type="submit">Button</button>
        </div>
    </form>
      </div>
    </div>
    </div>
   
    <div class="flex flex-col text-center w-full">


      <div class="p-4 md:w-full " style="margin-left: 0px; background-color: white">
        <form >
            <input class="bg-white rounded border border-gray-400 focus:outline-none focus:border-indigo-500 text-base px-4 py-2 mb-4" placeholder="search friends" type="text" name="jquery" value="{{ request.GET.jquery }}">
            <input type="submit" >
        </form>
         {% for profils in profile %}
          <h1>POST</h1>
         <div class="p-4 py-3 md:w-full" id="#{{profils.user}}">
     
        <div class="h-full border-2 border-gray-200 rounded-lg overflow-hidden py-3">

            {% if profils.profile_pic %}

          <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="{{profils.profile_pic.url}}" alt="blog">
          {% else %}
           <!-- <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="" alt="pls add profils pic"> -->
           {% endif %}
           <!-- post -->
             {% if profils.pic %}
             <a href="{% url 'facebook:post_User_Post_commt' profils.id %}">
          <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="{{profils.pic.url}}" alt="blog">
        </a>
          {% else %}
           <!-- <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="" alt="pls add profils pic"> -->
           {% endif %}
           <!-- post -->
          <div class="p-6">
            <h2 class="tracking-widest text-xs title-font font-medium text-gray-500 mb-1">{{ profils.user }}</h2>
            <h1 class="title-font text-lg font-medium text-gray-900 mb-3"><a href="{{ profils.get_profle_url }}" >{{ profils.user }}</a></h1>
           
           <!--  <div class="flex items-center flex-wrap ">
              <a class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0">Learn More
                <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M5 12h14"></path>
                  <path d="M12 5l7 7-7 7"></path>
                </svg>
              </a>
              <span class="text-gray-600 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-300">
                <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                  <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                  <circle cx="12" cy="12" r="3"></circle>
                </svg>1.2K
              </span>
              <span class="text-gray-600 inline-flex items-center leading-none text-sm">
                <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                  <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                </svg>6
              </span>
            </div> -->
          </div>
        </div>

      </div>
            {% endfor %}
    </div>
  </div>
</section>

{%endblock %}

templates/insta/post_User_Post_commt.html
 {% extends 'base.html'%}

  {% block contect %}
	<section class="text-gray-700 body-font relative">
  <div class="container  mx-auto" >
  	 <div class="p-2 w-full  border-t border-gray-200 text-center">
  	 	<div style="margin-left: 350px;">

	<img src="{{profile_D.pic.url}}" width="400px">
</div>
	{% for c in commt%}
	<ul>
		<li>{{c.you_msg}}  <small><i>{{c.commt}}</i></small></li>
	</ul>		
	
	{%endfor %}
	   <form method="POST">
            	{% csrf_token %}
           <input type="text" name="post" value="{{profile_D.id}}" hidden><br>
       <input type="text" name="you_msg" class="bg-white rounded border border-gray-400 focus:outline-none focus:border-indigo-500 text-base w-50 h-25"  placeholder="Comment" >
             
          <button class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg" type="submit">Comment</button>
        
    </form>
</div>
	</div></section>
	
{% endblock%}

templates/insta/profile_detail.html
 {% extends 'base.html'%}

  {% block contect %}


  <section class="text-gray-700 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-col">
    <div class="lg:w-4/6 mx-auto">
      <!-- <div class="rounded-lg h-64 overflow-hidden">
        <img alt="content" class="object-cover object-center h-full w-full" src="https://dummyimage.com/1200x500">
      </div> -->
      <div class="flex flex-col sm:flex-row mt-1">
        <div class="sm:w-1/3 text-center sm:pr-8 sm:py-8">
          <div class="w-20 h-20 rounded-full inline-flex items-center justify-center bg-gray-200 text-gray-400">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-15 h-10" viewBox="0 0 24 24">

         
          {% if profile_D.profile_pic %}
          <img src="{{profile_D.profile_pic.url}}" style="border-radius: 50%">
          {% else %}
          {% endif %}
                    <circle cx="12" cy="7" r="4"></circle>
          
            </svg>
          </div>
          <div class="flex flex-col items-center text-center justify-center">
            <h2 class="font-medium title-font mt-4 text-gray-900 text-lg">{{profile_D.user}}</h2>

              <!-- <h2 class="font-medium title-font mt-4 text-gray-900 text-lg">{{profile_D.user}}</h2> -->
             

            <div class="w-12 h-1 bg-indigo-500 rounded mt-2 mb-4"></div>
               <!-- <a class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg" href="" >ADD FRIEND</a> -->
               {% if check_frnds %}
               <a href="{{profile_D.get_add_frind_unfrnds_url}}" class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg" >unfrnd</a>
             {% else %}
                   <a href="{{ profile_D.get_add_frind_url }}" class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Add Friend </a>
                 {% endif %}
               

          </div>
        </div>
        <div class="sm:w-2/3 sm:pl-8 sm:py-8 sm:border-l border-gray-300 sm:border-t-0 border-t mt-4 pt-4 sm:mt-0 text-center sm:text-left">

        	{% for posts in post  %}
    
          <div class="p-4 md:w-full">
          	<a href="{% url 'facebook:post_User_Post_commt' posts.id %}">
        <div class="h-full border-2 border-gray-200 rounded-lg overflow-hidden">
          <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="{{ posts.pic.url }}" alt="blog">
      </a>
          <div class="p-6">
            <h2 class="tracking-widest text-xs title-font font-medium text-gray-500 mb-1">{{posts.uploaded_by}}</h2>
            <h1 class="title-font text-lg font-medium text-gray-900 mb-3"> {{ posts.msg }}</h1>
            <p class="leading-relaxed mb-3"> {{ posts.subject }}</p>

            <form method="POST">
            	{% csrf_token %}
           <input type="text" name="post" value="{{posts.id}}" hidden><br>
       <input type="text" name="you_msg" class="bg-white rounded border border-gray-400 focus:outline-none focus:border-indigo-500 text-base w-full h-25"  placeholder="Comment" >
               <div class="p-2 w-full">
          <button class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg" type="submit">Comment</button>
        </div>
    </form>
        {{commment_count|length }}
            <!-- <div class="flex items-center flex-wrap ">
              <a class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0">Learn More
                <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M5 12h14"></path>
                  <path d="M12 5l7 7-7 7"></path>
                </svg>
              </a>
              <span class="text-gray-600 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-300">
                <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                  <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                  <circle cx="12" cy="12" r="3"></circle>
                </svg>1.2K
              </span>
              <span class="text-gray-600 inline-flex items-center leading-none text-sm">
                <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                  <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                </svg>6
              </span>
            </div> -->
          </div>
        </div>
      
        
    </div>
    {% endfor%}
         
          
        </div>
      </div>
    </div>
  </div>
</section>
<!-- 
<h1>profile_D</h1>
{{ profile_D.user }}
{% if check_frnds %}


<a href="{{profile_D.get_add_frind_unfrnds_url}}">unfrnd</a>
{% else %}
<a href="{{ profile_D.get_add_frind_url }}">Add Friend </a>
{% endif %}

{#<form action="{{ profile_D.get_add_frind_url }}" method="POST">#}
{#    {% csrf_token %}#}
{#    {{ add_frnds.add_buy }}#}
{#    {{ add_frnds.add }}#}
{#  <input type="submit">#}
{#</form>#}
{{ profile_D.address }}
{{ profile_D.phone_no }}
{% block post %}
{% for posts in post  %}
    {{ posts.user }}
     <a href="#"><img src="{{ posts.pic.url }}" style="width: 100px">
    {{ posts.msg }}
    {{ posts.subject }}
    {% empty %}
    you post
{% endfor %}
{% endblock %}
{%endblock%} -->

templates/insta/register_user.html
<html lang="en">
<head>
	<title>Login V14</title>
	<meta charset="UTF-8">
	{% load static %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
				<form class="login100-form validate-form flex-sb flex-w" method="POST">
					   {% csrf_token %}
					<span class="login100-form-title p-b-32">
						Sign Up  <a href="{% url 'facebook:user_login' %}">login</a>
					</span>

					<span class="txt1 p-b-11">
						Username
					</span>
					<div class="wrap-input100 validate-input m-b-36" data-validate = "Username is required">
						<input class="input100" type="text" name="Username" >
						<span class="focus-input100"></span>
					</div>
					<span class="txt1 p-b-11">
						email
					</span>
					<div class="wrap-input100 validate-input m-b-36" data-validate = "Username is required">
						<input class="input100" type="email" name="email" >
						<span class="focus-input100"></span>
					</div>
					
					<span class="txt1 p-b-11">
						Password
					</span>
					<div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
						<input class="input100" type="password" name="password1" >
						<span class="focus-input100"></span>
					</div>
					
					<div class="flex-sb-m w-full p-b-48">
						

						
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit">
							Login
						</button>
					</div>

				</form>
			
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js"></script>

</body>
</html>